// Copyright (c) 2026 Wuji Labs Inc
import type { DictLazyAsset, LazyAsset } from '../index.js'
import { CompoundAssetReference } from './reference.js'
import type { TraceId } from './trace_id.js'

export type ValueOrRef<T> = T | CompoundAssetReference<T>

export const default_scope_id = 'default'

export type VersionId = TraceId & { readonly __sub_brand: 'VersionId' }
export type VersionType = 'output' | 'error' | 'workflow_definition' | 'implementation' | 'snapshot' // | "update" | `publish:${ScopeId}`
type VersionBase = {
  id: VersionId
  task_id: TaskId
  version_type_tag: VersionType
  asset: ValueOrRef<DictLazyAsset> | null
  parent_version_id: VersionId | null

  tags: string[]
  commit_message: string
  created_at: number // generated by TraceId(id).unix_ts_ms

  // executed_def_version_id?: VersionId; // for implementation and snapshot versions
}

/** Represents a successful output from a computational task */
export type OutputVersion = VersionBase & {
  version_type_tag: 'output'

  asset: ValueOrRef<DictLazyAsset> // output asset cannot be null
  executed_def_version_id: never
}

/** Represents a failed execution of a computational task */
export type ErrorVersion = VersionBase & {
  version_type_tag: 'error'

  executed_def_version_id: never
}

/** Represents a workflow definition that can be executed */
export type WorkflowDefinitionVersion = VersionBase & {
  version_type_tag: 'workflow_definition'

  asset: ValueOrRef<DictLazyAsset> // workflow definition asset cannot be null
  executed_def_version_id: never
}

/** Represents a binding between an Action and its implementation workflow definition */
export type ImplementationVersion = VersionBase & {
  version_type_tag: 'implementation'

  asset: null
  executed_def_version_id: VersionId
}

/** Represents a snapshot of a workflow execution's state */
export type SnapshotVersion = VersionBase & {
  version_type_tag: 'snapshot'

  asset: null
  executed_def_version_id: VersionId
}

export type Version = OutputVersion | ErrorVersion | WorkflowDefinitionVersion | ImplementationVersion | SnapshotVersion

export type ScopeId = string
export type TaskId = TraceId & { readonly __sub_brand: 'TaskId' }
export type Task = {
  id: TaskId
  scope_id: ScopeId
  action_id: ActionId
  direct_inputs: ValueOrRef<DictLazyAsset>
  parameters: ValueOrRef<DictLazyAsset>
  name: string
  description: string
  current_version_id: VersionId

  created_at: number // generated by TraceId(id).unix_ts_ms
}

// ActionId can be either a TraceId (for user-defined actions) or a system action identifier
export type SystemActionId = `core:${string}` // e.g., "core:define_action"
export type UserActionId = TaskId & { readonly __sub_sub_brand: 'UserActionId' }
export type ActionId = UserActionId | SystemActionId
export type Action = Task & {
  id: ActionId
  scope_id: ScopeId
  name: string
  description: string
  input_shape: LazyAsset
  output_shape: LazyAsset
}

// // For pipeline
// export type EdgeId = TraceId & { readonly __sub_brand: "EdgeId" };
// export type NodeId = TraceId & { readonly __sub_brand: "NodeId" };

// ==================================================================
// SYSTEM ACTIONS REGISTRY
// ==================================================================

/**
 * Creates a system action identifier from a system action name.
 * This returns a string-based identifier instead of a TraceId.
 */
export function createSystemActionId(systemActionName: string): SystemActionId {
  return systemActionName as SystemActionId
}

/**
 * System action definition for built-in actions
 */
export interface SystemAction {
  id: SystemActionId
  name: string
  description: string
  input_shape: LazyAsset
  output_shape: LazyAsset
}

/**
 * Registry of all built-in system actions (lazy-loaded)
 *
 * v14: Removed CORE_ORCHESTRATE_SUBMIT_PLAYER_INPUT, CORE_ORCHESTRATE_FAIL_PLAYER_TASK, CORE_ORCHESTRATE_RERUN_NODE
 * These mutations now use snapshot forking directly without creating job tasks
 */
let _systemActionIds: {
  CORE_DEFINE_ACTION: SystemActionId
  CORE_ORCHESTRATE_UPDATE_STALE: SystemActionId
} | null = null

function getSystemActionIds() {
  if (!_systemActionIds) {
    _systemActionIds = {
      CORE_DEFINE_ACTION: createSystemActionId('core:define_action'),
      CORE_ORCHESTRATE_UPDATE_STALE: createSystemActionId('core:orchestrate_update_stale'),
    }
  }
  return _systemActionIds
}

export const SYSTEM_ACTIONS = {
  get CORE_DEFINE_ACTION() {
    return getSystemActionIds().CORE_DEFINE_ACTION
  },
  get CORE_ORCHESTRATE_UPDATE_STALE() {
    return getSystemActionIds().CORE_ORCHESTRATE_UPDATE_STALE
  },
} as const

/**
 * Built-in system action definitions (lazy-loaded)
 */
let _systemActionDefinitions: Record<SystemActionId, SystemAction> | null = null

export function getSystemActionDefinitions(): Record<SystemActionId, SystemAction> {
  if (!_systemActionDefinitions) {
    _systemActionDefinitions = {
      [SYSTEM_ACTIONS.CORE_DEFINE_ACTION]: {
        id: SYSTEM_ACTIONS.CORE_DEFINE_ACTION,
        name: 'core:define_action',
        description: 'Creates a new action definition that can be used to build workflows',
        input_shape: {
          name: 'string',
          description: 'string',
        },
        output_shape: {
          actionId: 'ActionId',
        },
      },

      // Orchestrate actions (v12) - These are command tasks for async operations
      // Note: Asset parameters use CompoundAssetReference<DictLazyAsset> to ensure proper tracking in AssetReferences table
      //
      // v14: Only CORE_ORCHESTRATE_UPDATE_STALE remains. Other orchestration mutations now use
      // snapshot forking directly without creating job tasks (submitPlayerInput, failPlayerTask, requestNodeRerun)

      [SYSTEM_ACTIONS.CORE_ORCHESTRATE_UPDATE_STALE]: {
        id: SYSTEM_ACTIONS.CORE_ORCHESTRATE_UPDATE_STALE,
        name: 'core:orchestrate_update_stale',
        description: 'Command task to orchestrate updating all stale nodes in a workflow',
        input_shape: {
          wiTaskId: 'TraceId', // The WI Task ID (from ExecutionHandle mapping)
          staleNodeIds: 'string[] | null', // Optional list of specific node IDs to update
        },
        output_shape: {
          newSnapshotId: 'TraceId', // The new workflow snapshot ID created
          wiTaskId: 'TraceId', // The WI Task ID that was updated
          staleNodeIds: 'string[] | null', // Node IDs that were updated (or null for all)
          parentSnapshotId: 'TraceId', // The previous snapshot ID (for revert capability)
        },
      },
    }
  }
  return _systemActionDefinitions
}

/**
 * Checks if an ActionId corresponds to a system action
 */
export function isSystemAction(actionId: unknown): actionId is SystemActionId {
  return typeof actionId === 'string' && actionId.startsWith('core:')
}

/**
 * Gets a system action definition by ActionId
 */
export function getSystemAction(actionId: SystemActionId): SystemAction | null {
  return getSystemActionDefinitions()[actionId] || null
}

/**
 * Converts an ActionId to a database-storable format.
 * System actions are stored as their string identifiers.
 * User actions are stored as TraceIds.
 */
export function actionIdToDbFormat(actionId: ActionId): string {
  return actionId as string
}

/**
 * Converts a database-stored action ID back to ActionId type.
 * Checks if it's a system action string or a TraceId.
 */
export function dbFormatToActionId(dbValue: string): ActionId {
  return dbValue as ActionId
}
