// Copyright (c) 2026 Wuji Labs Inc
//
// Concrete data model for the playtiss SDK.
//
// These types extend the relationship generics from @playtiss/core with
// playtiss's specific opinions — how tasks are scoped, how versions are tagged,
// what fields a concrete Action carries. Third-party Collaboration Protocol
// tools are free to define their own concrete types that satisfy the same
// generics; this file is the Playtiss reference implementation.

import type {
  ActionId,
  AssetValue,
  DefaultTask,
  DictAsset,
  ScopeId,
  TaskId,
  TaskLike,
  ValueOrLink,
  VersionId,
  VersionLike,
} from '@playtiss/core'

export type {
  ActionId,
  NamespacedActionId,
  ScopeId,
  SystemActionId,
  TaskId,
  UserActionId,
  ValueOrLink,
  VersionId,
} from '@playtiss/core'
export { isSystemAction } from '@playtiss/core'

// ----------------------------------------------------------------------------
// VersionType (playtiss's concrete enumeration)
// ----------------------------------------------------------------------------

/**
 * Playtiss's concrete variants for a Version.
 *
 * Value literals match the wire format used in the GraphQL schema and SQLite
 * storage. Any future rename needs to touch the schema, the DB, and every
 * mutation / resolver / CLI comparison in lockstep.
 */
export type VersionType
  = | 'output'
    | 'error'
    | 'workflow_definition'
    | 'implementation'
    | 'snapshot'

type VersionBase = VersionLike<VersionId, TaskId, ValueOrLink<DictAsset>> & {
  version_type_tag: VersionType
  tags: string[]
  commit_message: string
  created_at: number // generated by TraceId(id).unix_ts_ms
}

/** Represents a successful output from a computational task */
export type OutputVersion = VersionBase & {
  version_type_tag: 'output'
  asset: ValueOrLink<DictAsset> // output asset cannot be null
  executed_def_version_id: never
}

/** Represents a failed execution of a computational task */
export type ErrorVersion = VersionBase & {
  version_type_tag: 'error'
  executed_def_version_id: never
}

/** Represents a workflow definition that can be executed */
export type WorkflowDefinitionVersion = VersionBase & {
  version_type_tag: 'workflow_definition'
  asset: ValueOrLink<DictAsset> // workflow definition asset cannot be null
  executed_def_version_id: never
}

/** Represents a binding between an Action and its implementation graph */
export type ImplementationVersion = VersionBase & {
  version_type_tag: 'implementation'
  asset: null
  executed_def_version_id: VersionId
}

/** Represents a snapshot of a graph execution's state (used for fork/replay) */
export type SnapshotVersion = VersionBase & {
  version_type_tag: 'snapshot'
  asset: null
  executed_def_version_id: VersionId
}

export type Version
  = | OutputVersion
    | ErrorVersion
    | WorkflowDefinitionVersion
    | ImplementationVersion
    | SnapshotVersion

// ----------------------------------------------------------------------------
// Task (concrete)
// ----------------------------------------------------------------------------

/**
 * Playtiss's concrete Task shape — satisfies TaskLike from @playtiss/core
 * and extends it with scope, naming, description, parameters, and timestamp.
 */
export type Task = DefaultTask & {
  scope_id: ScopeId
  parameters: ValueOrLink<DictAsset>
  name: string
  description: string
  created_at: number // generated by TraceId(id).unix_ts_ms
}

// ----------------------------------------------------------------------------
// Action (concrete)
// ----------------------------------------------------------------------------

/**
 * Playtiss's concrete Action shape — a Task that additionally declares
 * its input/output schemas. The `id` is narrowed to ActionId.
 */
export type Action = Task & {
  id: ActionId
  scope_id: ScopeId
  name: string
  description: string
  input_schema: AssetValue
  output_schema: AssetValue
}

// ----------------------------------------------------------------------------
// Compile-time conformance checks — verify our concrete types satisfy the
// relationship generics from @playtiss/core.
// ----------------------------------------------------------------------------

// Unused but load-bearing: breaks the build if conformance drifts.
type _assertTaskConforms = Task extends TaskLike<TaskId, ActionId, ValueOrLink<DictAsset>, VersionId> ? true : never
type _assertVersionConforms = Version extends VersionLike<VersionId, TaskId, ValueOrLink<DictAsset>> ? true : never
type _assertActionConforms = Action extends TaskLike<TaskId, ActionId, ValueOrLink<DictAsset>, VersionId> ? true : never

type _conformanceWitnesses = [_assertTaskConforms, _assertVersionConforms, _assertActionConforms]
