// Copyright (c) 2026 Wuji Labs Inc
import type { AssetValue, DictAsset } from '../index.js'
import type { AssetId } from './asset_id.js'
import type { TraceId } from './trace_id.js'

// ValueOrLink<T>: either an inline value or a CID string pointing to a stored asset.
export type ValueOrLink<T> = T | AssetId

export const default_scope_id = 'default'

export type VersionId = TraceId & { readonly __sub_brand: 'VersionId' }
export type VersionType = 'output' | 'error' | 'workflow_definition' | 'implementation' | 'snapshot'
type VersionBase = {
  id: VersionId
  task_id: TaskId
  version_type_tag: VersionType
  asset: ValueOrLink<DictAsset> | null
  parent_version_id: VersionId | null

  tags: string[]
  commit_message: string
  created_at: number // generated by TraceId(id).unix_ts_ms
}

/** Represents a successful output from a computational task */
export type OutputVersion = VersionBase & {
  version_type_tag: 'output'

  asset: ValueOrLink<DictAsset> // output asset cannot be null
  executed_def_version_id: never
}

/** Represents a failed execution of a computational task */
export type ErrorVersion = VersionBase & {
  version_type_tag: 'error'

  executed_def_version_id: never
}

/** Represents a workflow definition that can be executed */
export type WorkflowDefinitionVersion = VersionBase & {
  version_type_tag: 'workflow_definition'

  asset: ValueOrLink<DictAsset> // workflow definition asset cannot be null
  executed_def_version_id: never
}

/** Represents a binding between an Action and its implementation workflow definition */
export type ImplementationVersion = VersionBase & {
  version_type_tag: 'implementation'

  asset: null
  executed_def_version_id: VersionId
}

/** Represents a snapshot of a workflow execution's state */
export type SnapshotVersion = VersionBase & {
  version_type_tag: 'snapshot'

  asset: null
  executed_def_version_id: VersionId
}

export type Version = OutputVersion | ErrorVersion | WorkflowDefinitionVersion | ImplementationVersion | SnapshotVersion

export type ScopeId = string
export type TaskId = TraceId & { readonly __sub_brand: 'TaskId' }
export type Task = {
  id: TaskId
  scope_id: ScopeId
  action_id: ActionId
  direct_inputs: ValueOrLink<DictAsset>
  parameters: ValueOrLink<DictAsset>
  name: string
  description: string
  current_version_id: VersionId

  created_at: number // generated by TraceId(id).unix_ts_ms
}

// ActionId can be either a TraceId (for user-defined actions) or a system action identifier
export type SystemActionId = `core:${string}` // e.g., "core:define_action"
export type UserActionId = TaskId & { readonly __sub_sub_brand: 'UserActionId' }
export type ActionId = UserActionId | SystemActionId
export type Action = Task & {
  id: ActionId
  scope_id: ScopeId
  name: string
  description: string
  input_shape: AssetValue
  output_shape: AssetValue
}

// ==================================================================
// SYSTEM ACTIONS REGISTRY
// ==================================================================

/**
 * Creates a system action identifier from a system action name.
 * This returns a string-based identifier instead of a TraceId.
 */
export function createSystemActionId(systemActionName: string): SystemActionId {
  return systemActionName as SystemActionId
}

/**
 * System action definition for built-in actions
 */
export interface SystemAction {
  id: SystemActionId
  name: string
  description: string
  input_shape: AssetValue
  output_shape: AssetValue
}

/**
 * Registry of all built-in system actions (lazy-loaded)
 */
let _systemActionIds: {
  CORE_DEFINE_ACTION: SystemActionId
  CORE_ORCHESTRATE_UPDATE_STALE: SystemActionId
} | null = null

function getSystemActionIds() {
  if (!_systemActionIds) {
    _systemActionIds = {
      CORE_DEFINE_ACTION: createSystemActionId('core:define_action'),
      CORE_ORCHESTRATE_UPDATE_STALE: createSystemActionId('core:orchestrate_update_stale'),
    }
  }
  return _systemActionIds
}

export const SYSTEM_ACTIONS = {
  get CORE_DEFINE_ACTION() {
    return getSystemActionIds().CORE_DEFINE_ACTION
  },
  get CORE_ORCHESTRATE_UPDATE_STALE() {
    return getSystemActionIds().CORE_ORCHESTRATE_UPDATE_STALE
  },
} as const

/**
 * Built-in system action definitions (lazy-loaded)
 */
let _systemActionDefinitions: Record<SystemActionId, SystemAction> | null = null

export function getSystemActionDefinitions(): Record<SystemActionId, SystemAction> {
  if (!_systemActionDefinitions) {
    _systemActionDefinitions = {
      [SYSTEM_ACTIONS.CORE_DEFINE_ACTION]: {
        id: SYSTEM_ACTIONS.CORE_DEFINE_ACTION,
        name: 'core:define_action',
        description: 'Creates a new action definition that can be used to build workflows',
        input_shape: {
          name: 'string',
          description: 'string',
        },
        output_shape: {
          actionId: 'ActionId',
        },
      },

      [SYSTEM_ACTIONS.CORE_ORCHESTRATE_UPDATE_STALE]: {
        id: SYSTEM_ACTIONS.CORE_ORCHESTRATE_UPDATE_STALE,
        name: 'core:orchestrate_update_stale',
        description: 'Command task to orchestrate updating all stale nodes in a workflow',
        input_shape: {
          wiTaskId: 'TraceId',
          staleNodeIds: 'string[] | null',
        },
        output_shape: {
          newSnapshotId: 'TraceId',
          wiTaskId: 'TraceId',
          staleNodeIds: 'string[] | null',
          parentSnapshotId: 'TraceId',
        },
      },
    }
  }
  return _systemActionDefinitions
}

/**
 * Checks if an ActionId corresponds to a system action
 */
export function isSystemAction(actionId: unknown): actionId is SystemActionId {
  return typeof actionId === 'string' && actionId.startsWith('core:')
}

/**
 * Gets a system action definition by ActionId
 */
export function getSystemAction(actionId: SystemActionId): SystemAction | null {
  return getSystemActionDefinitions()[actionId] || null
}

/**
 * Converts an ActionId to a database-storable format.
 */
export function actionIdToDbFormat(actionId: ActionId): string {
  return actionId as string
}

/**
 * Converts a database-stored action ID back to ActionId type.
 */
export function dbFormatToActionId(dbValue: string): ActionId {
  return dbValue as ActionId
}
