// Copyright (c) 2026 Wuji Labs Inc
// Universal random bytes function using Web Crypto API
function randomBytes(size: number): Uint8Array {
  // Try Web Crypto API first (available in modern browsers and Node.js 16+)
  if (typeof crypto !== 'undefined' && crypto.getRandomValues) {
    const buffer = new Uint8Array(size)
    crypto.getRandomValues(buffer)
    return buffer
  }

  // Try Node.js crypto.webcrypto (Node.js 16+ fallback)
  if (typeof globalThis !== 'undefined' && globalThis.crypto && globalThis.crypto.getRandomValues) {
    const buffer = new Uint8Array(size)
    globalThis.crypto.getRandomValues(buffer)
    return buffer
  }

  // Fallback to Math.random (not cryptographically secure, but functional)
  console.warn('Using Math.random() fallback for crypto operations - not cryptographically secure')
  const buffer = new Uint8Array(size)
  for (let i = 0; i < size; i++) {
    buffer[i] = Math.floor(Math.random() * 256)
  }
  return buffer
}

/**
 * Playtiss TraceID (UUIDv8)
 *
 * A custom UUIDv8 implementation for Playtiss's TraceID.
 * It is a 128-bit identifier designed for time-ordered, auditable, and unique
 * identification of entities within the system.
 *
 * The layout conforms to the UUID v8 specification (RFC 9562), ensuring
 * compatibility with standard UUID tools and libraries.
 *
 * ### Bit Layout (128 bits)
 *
 * | Section         | Bits    | Field           | Description                                                 |
 * |-----------------|---------|-----------------|-------------------------------------------------------------|
 * | Time            | 0-47    | unix_ts_ms      | 48-bit UNIX timestamp in milliseconds. Big-endian.          |
 * | Version         | 48-51   | ver             | 4-bit version, fixed to `1000` (8).                         |
 * | Custom Data A   | 52-63   | op_id_part1     | First 12 bits of the 48-bit Operation ID.                   |
 * | Variant         | 64-65   | var             | 2-bit variant, fixed to `10` (RFC 4122).                    |
 * | Custom Data B   | 66-67   | reserved        | 2-bit reserved field, fixed to `00`.                        |
 * | (continued)     | 68-103  | op_id_part2     | Remaining 36 bits of the 48-bit Operation ID.               |
 * | (continued)     | 104-127 | seq             | 24-bit sequence number, reset every millisecond.            |
 *
 *
 *  0                   1                   2                   3
 *  0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
 * +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 * |                           unix_ts_ms                          |
 * +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 * |          unix_ts_ms           |  ver  |     op_id_part1       |
 * +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 * |var|0 0|                    op_id_part2                        |
 * +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 * |  op_id_part2  |                       seq                     |
 * +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 *
 * This corresponds to the UUID format: `XXXXXXXX-XXXX-8XXX-8XXX-XXXXXXXXXXXX`,
 * as the variant is `10` and the reserved bits are `00`.
 */

export type TraceId = string & { readonly __brand: 'TraceId' }

const byteToHex: string[] = []
for (let i = 0; i < 256; ++i) {
  byteToHex.push((i + 0x100).toString(16).substring(1))
}

function stringify(arr: Uint8Array): TraceId {
  if (arr.length !== 16) {
    throw new TypeError('Invalid argument; expected a 16-byte array')
  }
  return (
    byteToHex[arr[0]]
    + byteToHex[arr[1]]
    + byteToHex[arr[2]]
    + byteToHex[arr[3]]
    + '-'
    + byteToHex[arr[4]]
    + byteToHex[arr[5]]
    + '-'
    + byteToHex[arr[6]]
    + byteToHex[arr[7]]
    + '-'
    + byteToHex[arr[8]]
    + byteToHex[arr[9]]
    + '-'
    + byteToHex[arr[10]]
    + byteToHex[arr[11]]
    + byteToHex[arr[12]]
    + byteToHex[arr[13]]
    + byteToHex[arr[14]]
    + byteToHex[arr[15]]
  ).toLowerCase() as TraceId
}

/**
 * Generates a 48-bit (6-byte) random Operation ID.
 * According to the Playtiss specification, this should be generated once per
 * logical operation (e.g., a single CLI command execution).
 */
export const generateOperationId = (): Uint8Array => randomBytes(6)

export class TraceIdGenerator {
  private readonly timestamp: number
  private readonly operationId: Uint8Array
  private sequence: number

  /**
   * Creates a new TraceID generator for a specific logical operation.
   * The generator is initialized with the current timestamp and a given
   * operation ID. It maintains an internal sequence counter for all IDs
   * generated by this instance.
   *
   * Note: This generator 'freezes' the timestamp at the moment of creation.
   * All IDs produced by this instance will share the same timestamp.
   *
   * @param operationId The 48-bit (6-byte) Operation ID. If not provided,
   * a random one will be generated.
   */
  constructor(operationId?: Uint8Array) {
    if (operationId) {
      if (operationId.length !== 6) {
        throw new Error('Provided Operation ID must be 6 bytes (48 bits).')
      }
      this.operationId = operationId
    }
    else {
      this.operationId = generateOperationId()
    }
    this.timestamp = Date.now()
    this.sequence = 0
  }

  /**
   * Generates a new TraceID as a 16-byte buffer.
   * @returns A 16-byte Uint8Array representing the TraceID.
   */
  public generateBytes(): Uint8Array {
    this.sequence++
    if (this.sequence >= 2 ** 24) {
      throw new Error(
        'Sequence number overflow. More than 2^24 IDs generated with this generator instance.',
      )
    }

    const buffer = new Uint8Array(16)
    const timestamp = this.timestamp

    // Set 48-bit timestamp
    buffer[0] = timestamp / 2 ** 40
    buffer[1] = timestamp / 2 ** 32
    buffer[2] = timestamp / 2 ** 24
    buffer[3] = timestamp / 2 ** 16
    buffer[4] = timestamp / 2 ** 8
    buffer[5] = timestamp

    const opIdBigInt
      = (BigInt(this.operationId[0]) << 40n)
        | (BigInt(this.operationId[1]) << 32n)
        | (BigInt(this.operationId[2]) << 24n)
        | (BigInt(this.operationId[3]) << 16n)
        | (BigInt(this.operationId[4]) << 8n)
        | BigInt(this.operationId[5])

    const opIdPart1 = Number(opIdBigInt >> 36n) // 12 bits
    const opIdPart2 = opIdBigInt & 0xfffffffffn // 36 bits

    // Set version (8) and 12-bit op_id_part1
    buffer[6] = 0x80 | (opIdPart1 >> 8)
    buffer[7] = opIdPart1 & 0xff

    // Set variant (10), reserved (00), 36-bit op_id_part2, and 24-bit sequence
    const high4OfOpIdPart2 = Number(opIdPart2 >> 32n) & 0x0f
    buffer[8] = 0x80 | high4OfOpIdPart2

    const rem32OfOpIdPart2 = opIdPart2 & 0xffffffffn
    buffer[9] = Number(rem32OfOpIdPart2 >> 24n)
    buffer[10] = Number(rem32OfOpIdPart2 >> 16n)
    buffer[11] = Number(rem32OfOpIdPart2 >> 8n)
    buffer[12] = Number(rem32OfOpIdPart2 & 0xffn)

    buffer[13] = (this.sequence >> 16) & 0xff
    buffer[14] = (this.sequence >> 8) & 0xff
    buffer[15] = this.sequence & 0xff

    return buffer
  }

  /**
   * Generates a new TraceID string.
   * @returns A TraceID formatted as a UUID string.
   */
  public generate(): TraceId {
    return stringify(this.generateBytes())
  }
}

/**
 * Generate a new TraceID for a specific logical operation.
 * @param operationId The 48-bit (6-byte) Operation ID. If not provided,
 * a random one will be generated.
 * @returns A TraceID formatted as a UUID string.
 */
export const generateTraceId = (operationId?: Uint8Array): TraceId => {
  return new TraceIdGenerator(operationId).generate()
}

/**
 * Generate a new TraceID in bytes.
 * @returns A 16-byte Uint8Array representing the TraceID.
 */
export const generateTraceIdBytes = (operationId?: Uint8Array): Uint8Array => {
  return new TraceIdGenerator(operationId).generateBytes()
}

/**
 * Parse a TraceID string into its components.
 * @param id The TraceID string to parse.
 * @returns An object containing the timestamp, operation ID, and sequence number.
 */
export const parseTraceId = (id: TraceId): { timestamp: number, operationId: Uint8Array, sequence: number } => {
  const buffer = new Uint8Array(16)

  // Convert hex string to buffer
  const hexParts = id.replace(/-/g, '')
  if (hexParts.length !== 32) {
    throw new Error('Invalid TraceID format')
  }

  // Convert hex strings to bytes
  for (let i = 0; i < 16; i++) {
    buffer[i] = parseInt(hexParts.slice(i * 2, i * 2 + 2), 16)
  }

  // Extract timestamp (48 bits)
  const timestamp = (BigInt(buffer[0]) << 40n) | (BigInt(buffer[1]) << 32n) | (BigInt(buffer[2]) << 24n) | (BigInt(buffer[3]) << 16n) | (BigInt(buffer[4]) << 8n) | BigInt(buffer[5])

  // Extract operation ID (48 bits)
  // opIdHead is the first 16 bits of the operation ID, removing the version and variant bits
  const opIdHeadPart1
    = ((buffer[6] << 8)
      | (buffer[7])) & 0xfff // 12 bits
  const opIdHeadPart2 = buffer[8] & 0xf // 4 bits
  const opIdHead = (opIdHeadPart1 << 4) | opIdHeadPart2

  return {
    timestamp: Number(timestamp),
    operationId: new Uint8Array([
      opIdHead >> 8,
      opIdHead & 0xff,
      // opIdTail is the last 32 bits of the operation ID, removing the sequence bits
      buffer[9],
      buffer[10],
      buffer[11],
      buffer[12],
    ]),
    sequence: (buffer[13] << 16 | buffer[14] << 8 | buffer[15]),
  }
}

/**
 * A regular expression to validate the specific format of a Playtiss TraceID.
 * It expects a UUID string where the version is 8 and the variant bits
 * combined with the reserved bits also result in the 9th byte starting with '8'.
 * Format: `XXXXXXXX-XXXX-8XXX-8XXX-XXXXXXXXXXXX`
 */
const TRACE_ID_REGEX
  = /^[0-9a-f]{8}-[0-9a-f]{4}-8[0-9a-f]{3}-8[0-9a-f]{3}-[0-9a-f]{12}$/i

/**
 * Type guard to check if a given value is a valid Playtiss TraceID string.
 * @param id The value to check.
 * @returns True if the value is a string that matches the TraceID format.
 */
export function isTraceId(id: unknown): id is TraceId {
  return typeof id === 'string' && TRACE_ID_REGEX.test(id)
}
