// Copyright (c) 2026 Wuji Labs Inc
/**
 * Pipeline-runner domain types extracted from GraphQL codegen output.
 *
 * These are convenience aliases for the query response shapes generated by
 * graphql-codegen. They unwrap the nullable root field and array wrappers
 * so callers get clean non-nullable types.
 */
import type {
  GetRevisionQuery,
  GetTaskExecutionStateQuery,
  GetTaskQuery,
} from '../__generated__/graphql.js'

/** Task record as returned by getTask query */
export type Task = NonNullable<GetTaskQuery['getTask']>

/** Workflow revision node state as returned by getRevision query */
export type workflowRevisionNodeState = GetRevisionQuery extends {
  getRevision?: { nodes: Array<infer N> } | null
} ? NonNullable<N> : never

/** Task execution state as returned by getTaskExecutionState query */
export type workflowTaskExecutionState = NonNullable<GetTaskExecutionStateQuery['getTaskExecutionState']>
